In [12]:
import pandas as pd
from pathlib import Path

In [13]:
#csv_path = "Project_4/Bedbug_Reporting.csv"
glassdoor_data_df = pd.read_csv("clean_glasss_door.csv")
glassdoor_data_df.head()

,Unnamed: 0,firm,date_review,job_title,current,location,overall_rating,work_life_balance,culture_values,diversity_inclusion,career_opp,comp_benefits,senior_mgmt
0,50,AFH-Wealth-Management,2020-10-01,Office Administrator,"Former Employee, more than 3 years","Bromsgrove, England, England",2,1.0,3.0,1.0,1.0,2.0,2.0
1,51,AFH-Wealth-Management,2021-02-05,Quality Control,Former Employee,"Birmingham, England, England",1,3.0,1.0,2.0,1.0,1.0,1.0
2,52,AFH-Wealth-Management,2021-02-07,IFA Administrator,"Former Employee, less than 1 year","Bromsgrove, England, England",4,3.0,3.0,4.0,4.0,4.0,2.0
3,53,AFH-Wealth-Management,2021-02-07,Investment Operations,"Former Employee, more than 1 year","Birmingham, England, England",3,5.0,5.0,4.0,3.0,1.0,2.0
4,60,AFH-Wealth-Management,2021-05-12,Client Engagement Executive,"Former Employee, less than 1 year","Birmingham, England, England",1,1.0,2.0,1.0,1.0,1.0,1.0

In [14]:
 df = glassdoor_data_df.dropna()

In [15]:
df.columns

Index(['Unnamed: 0', 'firm', 'date_review', 'job_title', 'current', 'location',
       'overall_rating', 'work_life_balance', 'culture_values',
       'diversity_inclusion', 'career_opp', 'comp_benefits', 'senior_mgmt'],
      dtype='object')

In [26]:
for i, genre in enumerate(df['current']):
    if genre == 'Former Employee':
        df.loc[i, 'employee_position'] = 1
    elif genre == 'Former Employee, less than 1 year':
        df.loc[i, 'employee_position'] = 2
    elif genre == 'Former Employee, more than 1 year':
        df.loc[i, 'employee_position'] = 3
    elif genre == 'Former Employee, more than 3 years':
        df.loc[i, 'employee_position'] = 4
    elif genre == 'Former Employee, more than 5 years':
        df.loc[i, 'employee_position'] = 5
    elif genre == 'Former Employee, more than 8 years':
        df.loc[i, 'employee_position'] = 6
    elif genre == 'Former Employee, more than 10 years':
        df.loc[i, 'employee_position'] = 7
    elif genre == 'Current Employee':
        df.loc[i, 'employee_position'] = 8
    elif genre == 'Current Employee, less than 1 year':
        df.loc[i, 'employee_position'] = 9
    elif genre == 'Current Employee, more than 1 year':
        df.loc[i, 'employee_position'] = 10
    elif genre == 'Current Employee, more than 3 year':
        df.loc[i, 'employee_position'] = 11
    elif genre == 'Current Employee, more than 5 year':
        df.loc[i, 'employee_position'] = 12
    elif genre == 'Current Employee, more than 8 year':
        df.loc[i, 'employee_position'] = 13
    elif genre == 'Current Employee, more than 10 year':
        df.loc[i, 'employee_position'] = 14
print(df['employee_position'])

0         4.0
1         1.0
2         2.0
3         3.0
4         2.0
         ...
108539    2.0
108540    8.0
108541    9.0
108542    NaN
108543    NaN
Name: employee_position, Length: 108544, dtype: float64

In [22]:
df.head(5)

,Unnamed: 0,firm,date_review,job_title,current,location,overall_rating,work_life_balance,culture_values,diversity_inclusion,career_opp,comp_benefits,senior_mgmt,Genre
0,50,AFH-Wealth-Management,2020-10-01,Office Administrator,"Former Employee, more than 3 years","Bromsgrove, England, England",2,1.0,3.0,1.0,1.0,2.0,2.0,4.0
1,51,AFH-Wealth-Management,2021-02-05,Quality Control,Former Employee,"Birmingham, England, England",1,3.0,1.0,2.0,1.0,1.0,1.0,1.0
2,52,AFH-Wealth-Management,2021-02-07,IFA Administrator,"Former Employee, less than 1 year","Bromsgrove, England, England",4,3.0,3.0,4.0,4.0,4.0,2.0,2.0
3,53,AFH-Wealth-Management,2021-02-07,Investment Operations,"Former Employee, more than 1 year","Birmingham, England, England",3,5.0,5.0,4.0,3.0,1.0,2.0,3.0
4,60,AFH-Wealth-Management,2021-05-12,Client Engagement Executive,"Former Employee, less than 1 year","Birmingham, England, England",1,1.0,2.0,1.0,1.0,1.0,1.0,2.0

In [27]:
df.to_csv('converted_job_position_column.csv', index=False)